#!/bin/bash

sudo rm -rf build_result
sudo mkdir build_result
cd build_result
sudo pyinstaller ../../PyGrd.py --clean -y -n 'PyGrd' --onedir --name PyGrd -i '/icons/PyGrd_96.ico' --add-data '../../config.txt:.' --add-data '../../modules/setting.ini:modules' --add-data '../../icons:icons' --add-data '../../modules/css_styling.css:modules' --log-level DEBUG > pyinstaller_out.txt
sudo rm -rf dist/PyGrd/share/icons/
sudo rm -rf dist/PyGrd/share/themes/
